interface.c
BUF_SIZE
Referenced by interpretador.
n
Referenced by inicializar_estado, interpretador, position, printBoard, printInFile.
FILE* fp
Referenced by interpretador, jogadasInFile, printInFile.
bool finish
Referenced by interpretador.
void jogadas(ESTADO *e)
References ESTADO::jogadas, ESTADO::num_jogadas.
Referenced by interpretador, printBoard.
int distancia_euclidiana(char x, char y, ESTADO *e)
References ESTADO::jogador_atual.
Referenced by interpretador.
void jogadasInFile(ESTADO *e)
References fp, ESTADO::jogadas.
Referenced by interpretador.
void printBoard(ESTADO *e)
Esta função constrói os tabuleiros.
Esta função funciona através de ciclos onde o primeiro ciclo constroi a primeira linha do tabuleiro, sendo q isto só se repete até i < n. ou seja até i < 8 construindo assim um tabuleiro com 8 linhas e colunas. No fim é aplicado printf ("\n ") para introduzir espaços entre o tabuleiro e onde o jogador insere a jogada. e Apontador para o estado
References jogadas, ESTADO::jogador_atual, n, ESTADO::num_jogadas, ESTADO::tab.
Referenced by interpretador, main, position.
void printInFile(ESTADO *e)
References DOIS, fp, n, PRETA, ESTADO::tab, UM, VAZIO.
Referenced by interpretador.
void position(ESTADO *e, int valor)
References BRANCA, COORDENADA::coluna, DOIS, ESTADO::jogadas, ESTADO::jogador_atual, COORDENADA::linha, n, ESTADO::num_jogadas, PRETA, printBoard, ESTADO::tab, ESTADO::ultima_jogada, UM, VAZIO.
Referenced by interpretador.
int interpretador(ESTADO *e)
O interpretador é a função aonde estão guardados os vários comandos.
O interpretador também verifica se uma jogada introduzida é válida , dá o jogo como finalizado através da função check_finish e dá print a indicar o respectivo vencedor. O comandos "gr" guarda o estado do jogo num ficheiro. O comando "ler " lê o estado do jogo a partir do ficheiro guardado em "gr". O comando "jog" verifica as posiçães adjacentes que estão livres a partir da posição da peça branca e efetua uma jogada aleatória (Caso a peça branca esteja numa posição consecutiva á casa de vitória, essa jogada será sempre prioridade). O comando "jog2"(estratégia da distância_euclidiana) procura todas as jogadas possíveis a partir da posição em que a peça branca se encontra , depois percorre todas essas posições possíveis e calcula a distância euclidiana para ,assim, saber qual a é a posição mais perto da casa de vitória.(Caso a peça branca esteja numa posição consecutiva á casa de vitória, essa jogada será sempre prioridade). e Apontador para o estado
References add_position, BRANCA, BUF_SIZE, check_finish, COORDENADA::coluna, criar_lista, devolve_cabeca, distancia_euclidiana, DOIS, finish, fp, insere_cabeca, jogadas, ESTADO::jogadas, jogadasInFile, ESTADO::jogador_atual, COORDENADA::linha, lista_esta_vazia, n, ESTADO::num_jogadas, position, printBoard, printInFile, remove_cabeca, ESTADO::tab, ESTADO::ultima_jogada, UM, VAZIO.
Referenced by main.