lista.h
typedef struct lista CABECA
typedef struct lista * LISTA
LISTA criar_lista()
Função que cria uma lista inicialmente vazia A função define a cabeça da lista e a cauda como vazias e dá return desses valores.
x É Uma lista Lista x vazia
References lista::cabeca, lista::proximo.
Referenced by interpretador.
LISTA insere_cabeca(LISTA L, void *valor)
Insere um valor na cabeça da lista.
l É uma Lista x É uma lista valor É um valor aleatório (if(L->cabeca == NULL)) return da lista L com o valor na cabeça (else) return da lista x
References lista::cabeca, lista::proximo.
Referenced by interpretador.
void* devolve_cabeca(LISTA L)
Devolve a cabeça da lista.
l É uma lista cabeça da lista L
References lista::cabeca.
Referenced by interpretador.
LISTA proximo(LISTA L)
Devolve a cauda da lista.
l É uma lista a cauda da lista L
References lista::proximo.
LISTA remove_cabeca(LISTA L)
Remove a cabeça da lista (libertando o espaço ocupado) e devolve a cauda Igualamos a lista x á cauda da lista L e damos return á lista x.
l É uma lista x É uma lista Lista x
References lista::cabeca, lista::proximo.
Referenced by interpretador.
int lista_esta_vazia(LISTA L)
Devolve verdareiro se a lista é vazia.
(f(L->cabeca == NULL && L->proximo == NULL)) True (else) False
References lista::cabeca, lista::proximo.
Referenced by interpretador.